### PR TITLE
update certificates with verification links

### PR DESCRIPTION
**Pull request by thealphadollar**
The PR updates the certificates with a verification link that can be opened to view that the certificate was indeed provided by KOSS.

The files are now hosted at 

```python
https://kossiitkgp.org/public-files/KWoC/2018-Certificates/KWoC18- + name.replace(" ", "%20") + .pdf
```

Below is a sample of the same.

screenshot from 2019-02-24 02-00-42

### CODE REVIEW

**Review by xypnox — APPROVED** [review]
LGTM

**Review by xypnox — APPROVED** [review]

**Comment by arnav-t** [comment]
Shouldn't the link in the sample certificate be `.../KWoC18-Abhijit%20Ramesh.pdf` instead of `.../Abhijit%20Ramesh.pdf`?

**Comment by thealphadollar** [comment]
Fixed @arnav-t

**Review by arnav-t — APPROVED** [review]

**Comment by OrkoHunter** [comment]
Great work @thealphadollar!

I do not understand the purpose of adding `KWoC18-` before the name. It is already under the index of `KWoC/2018-Certificates`, so the new change is kind of redundant, isn't it?

**Comment by thealphadollar** [comment]
Yes, but I kept the formatting same across all platforms (certificate name,
url etc) since we were (and may in future) face issues regarding
inconsistency in name and url format when generated from different sources.

cc/ @arnav-t

**Comment by OrkoHunter** [comment]
Cool!

**Review by themousepotato — APPROVED** [review]
Looks awesome to me!

**Comment by Ayushk4** [comment]
How about modifying the url to something like similar to what coursera does? - `coursera.org/verify/6DZP7LQJLGSU`. This may look more professional if we generate a unique URL. Something like `kossiitkgp.org/public-files/KWoC/KWoC18-Mentee/<UniqueKey>`

**Comment by thealphadollar** [comment]
As I said, the input to output ratio is not worth it.

Also, it'll be a lot of work syncing the text placement process with hash
creation and link generation.

**Comment by arnav-t** [comment]
I agree with @thealphadollar
It looks pretty good as is. It's just not worth putting in so much effort
for something 99% of the people won't even notice like a unique key in the
URL.

**Pull request merged**
